version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: austin
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: ardelis
    ports:
      - "5432:5432"
    networks:
      - dev-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - dev-network
    environment:
      DATABASE_URL: postgres://austin:12345678@db:5432/ardelis

networks:
  dev-network:

volumes:
  postgres_data:
